[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

address = "0.0.0.0"
port = 8501

[theme]
base="light"
primaryColor="#1f77b4"

[browser]
serverAddress = "localhost"
gatherUsageStats = false
